travis:
  secure:
    BINSTAR_TOKEN: RbGg77x1Cjp9tfhsNyfwwGdr83DuAc+AAUA/x79zz3+07m/X4rllAVGrca06pwRCSdJAUd5ygjA5R+wPjs9wADmqaxU2u0NKulO/rMFs7mB8xzUXfBHVtvAt1YIM97GP/5kLDJ35yL3/c8BtZh0HSahdt0oVYx/6VeOMq6zXjdaVj2aVoaIEUg3jLVjq6psGEjUV/bvgejLtsHv246ij4OcQ9d0fe3/N9nOOYKJA7u9J/+oHf0XbbvlHEmbK6c3qb5A0VdtRUsWIKJg37zOM+/sayeXHZeUjj0mDSq6Nm1xaiX4yZblo4kZcce3amR4XZTZuH7g46OFbTrNY7WzpPGzsxBBVC3tEEpSgs6RTWJCUGWQvNzJ4ZCOO4q3Z5wFtE/tySlxCU2yVitxQUj0sag77WJ2Wrj+Oe9XwLwCvJvEXRWf8CzT/UgXyDVBGBbSoT4uBtefmF685zVRYkhhOWbZaLAP7REV61LzCRz0PveUqBUhRrUw/FD6SpPTcPQBP0qqlLl5paCZWbrKtu+WXeSdmkMB/Cc3LSWzUHr8iDeEC2oXn2li2ljNNqUJciM06YAn7yY3edCylQ3sGrbzVqao0s3LyLdOuT3KZU4aKXt5johTHNDi/sQmzr6wTpE1OODCkER6Nv8U0bdW3TKVGpaDLXR2G30SDabpUB9PPehU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
