appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TUWXJ7Jhj60vZ/rJZ5m/3PkwZSp3FnxUwklwwbTFevJ6WqQTxBgN3wZkVliqp/BQactyChxNtWvCpb0mXb1gSsWRrzdMKv6qmAFN72qQQ2RqHMFY+SGBUh350XZdx1u4pRriFXYI+HKBdjvj5LyJWSbjCR/zxGMXAYYhjg0w2TFVKrcxuvn8odPnyEW7ixd5/tnL5Ei/tiyGewhTU0CzvpA6SdlKBbXdMqQuO2vS8LSL8n6nrjMpGEi+hL4Ji7gnyEo+M4eYX2jEWrqwleZtpujrYosUTLQvJ6h1p5gjwNTSnp9IKPbagcQ4Gy1BPZnxPZI2FR3k04AAVLNqRj/6BEpzltjfpFsePI8S//HZ6ZYDjuFrwC7/Zq98X5PfNbL+nLxXATa6U6krmspl+XgjeS8hpbkKlsZXgfHRtxOo1m/jcY9pBn8iK+9MsCs9Ugh+77LlbF2/Dv26DGb+UsWDa+K3zcAjXj/ctfx8zRyS3dd64pODdrW9C4j/2Vs/A7m06JTdZNfoEpXLcmT5vFNzbDwDSywoelxR0L8jXPlaed6CXnxULfPHWPucbTUt0Y9I7SeQEADPlDUiKzu5h/7AkOSh4sd57VchBWaQXdpGMl/wse3/i2zgrN6JEpwXve0C54lyHYcctPQZAM4TjTPzvBFbOorysUwqyxCodXJtbl4=
conda_forge_output_validation: true
